# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 21582aa3bea09c297864a0dbda3d48c0fe1a929b57fd4eb0b2eb047e7e023cc1f6a427d92fefeb74d78916ae0624c3e36aa021e4b82316ecd0dd0716a15a0e62
  app_id: 611531139007860
  secret_key: f15641fa1e4380b1bebbc6c29d9578e7
  callback_url: http://localhost:3000/



test:
  secret_key_base: 20f8dd55d518bd0d41066af4b21f69e352e0d3ef24624e9c12923c0607cc9bf81dc58118ea90576b71858c9d4270ba9b8f4b5d3ccc1243a98bee16e383b68ca2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
